# Generated by Django 4.0.5 on 2022-06-07 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': (['last_name', 'first_name'],), 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
